spring.application.name=hotelTestApp
server.port=8092
server.servlet.context-path=/property-view

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=none
